export const auditActions = [
  "USER_CREATED",
  "USER_UPDATED",
  "USER_ACTIVATED",
  "USER_DEACTIVATED",
  "UPT_CREATED",
  "UPT_UPDATED",
  "UPT_ACTIVATED",
  "UPT_DEACTIVATED",
  "PERIOD_CREATED",
  "PERIOD_UPDATED",
  "INDICATOR_CREATED",
  "INDICATOR_UPDATED",
  "INDICATOR_APPROVED",
  "INDICATOR_REJECTED",
  "DOCUMENT_CREATED",
  "DOCUMENT_UPDATED",
  "DOCUMENT_APPROVED",
  "DOCUMENT_REJECTED",
  "REPORT_CREATED",
  "REPORT_UPDATED",
  "REPORT_SUBMITTED",
  "REPORT_REVIEW_COMMENTED",
  "REPORT_REVISION_REQUESTED",
  "REPORT_REVIEWED",
  "REPORT_APPROVED",
  "ATTACHMENT_UPLOADED",
  "ATTACHMENT_DELETED",
  "REPORTS_EXPORTED",
] as const;

export const auditEntityTypes = [
  "User",
  "UPT",
  "ReportingPeriod",
  "Indicator",
  "RequiredDocument",
  "Report",
  "Attachment",
  "ReportExport",
] as const;

export const auditActionLabels: Record<string, string> = {
  USER_CREATED: "Pengguna dibuat",
  USER_UPDATED: "Pengguna diubah",
  USER_ACTIVATED: "Pengguna diaktifkan",
  USER_DEACTIVATED: "Pengguna dinonaktifkan",
  UPT_CREATED: "UPT dibuat",
  UPT_UPDATED: "UPT diubah",
  UPT_ACTIVATED: "UPT diaktifkan",
  UPT_DEACTIVATED: "UPT dinonaktifkan",
  PERIOD_CREATED: "Periode dibuat",
  PERIOD_UPDATED: "Periode diubah",
  INDICATOR_CREATED: "Indikator dibuat",
  INDICATOR_UPDATED: "Indikator diubah",
  INDICATOR_APPROVED: "Indikator disahkan",
  INDICATOR_REJECTED: "Indikator ditolak",
  DOCUMENT_CREATED: "Dokumen wajib dibuat",
  DOCUMENT_UPDATED: "Dokumen wajib diubah",
  DOCUMENT_APPROVED: "Dokumen wajib disahkan",
  DOCUMENT_REJECTED: "Dokumen wajib ditolak",
  REPORT_CREATED: "Laporan dibuat",
  REPORT_UPDATED: "Laporan diubah",
  REPORT_SUBMITTED: "Laporan diajukan",
  REPORT_REVIEW_COMMENTED: "Komentar reviu ditambahkan",
  REPORT_REVISION_REQUESTED: "Revisi laporan diminta",
  REPORT_REVIEWED: "Laporan selesai direviu",
  REPORT_APPROVED: "Laporan disetujui",
  ATTACHMENT_UPLOADED: "Lampiran diunggah",
  ATTACHMENT_DELETED: "Lampiran dihapus",
  REPORTS_EXPORTED: "Laporan diekspor",
};

export const auditEntityLabels: Record<string, string> = {
  User: "Pengguna",
  UPT: "UPT",
  ReportingPeriod: "Periode",
  Indicator: "Indikator",
  RequiredDocument: "Dokumen wajib",
  Report: "Laporan",
  Attachment: "Lampiran",
  ReportExport: "Ekspor laporan",
};
